### ISSUE TITLE
ErrorLevel and Pause

### ISSUE THREAD

**Issue by thelonelyprogrammer** [JPCERTCC/EmoCheck#7]
It's cumbersome to integrate your script into 3rd party monitoring solutions since it always pauses output and because it doesn't return a proper ERRORLEVEL.

Please remove the pause instruction and return an ERRORLEVEL of 1 if emotet is found.

I tried to improve your tool myself with a pull request and also sent an email, both have been ignored unfortunately.

**Comment by t-tani** [comment]
I merged your pull request.
ERRORLEVEL is set as you requested.

If you don't want to pause, please use the `/quiet` option. It will disable the pause and terminal output.

**Comment by thelonelyprogrammer** [comment]
Thank you for adding a dynamic ERRORLEVEL, much appreciated. It wasn't possible to use the /quiet option before since the ERRORLEVEL, was always zero. Now that it's dynamic, we can use the quiet option. I'm still not a fan of the "pause" (most tools don't have it), but it's doable since you have the /quiet option. Thanks for everything.
